### ISSUE TITLE
TO-DO

### ISSUE THREAD

**Issue by SimoneBiotto** [LeoRc01/GameBased#19]
- [x] Completare search (Roxas)
- [x] lruCache
- [x] change profilepicture 
- [x] change username
- [x] forgot password
- [x] mettere i games dentro i dialog
- [x] mettere i dialog in ogni fragment
- [x] mettere i bordi tondi al dialog
- [x] implementare dialog per la collection
- [x] sistemare screenshot fullscreen
- [x] aggiungere la possibilita di entrare senza login, togliendo la possibilita dei favorites
- [x] change language
- [x] refactor settings
- [x] fix login as guest
